export const badJobs = [
	'Ayurveda Healer',
	'Bike Courier',
	'Body Painter',
	'Feng Shui Consultant',
	'Nail Polish Namer',
	'Veterinary Acupuncturist',
	'Pick-up Artist Instructor',
	'Security Guard',
	'Project Manager',
	'Truck Driver',
	'Dishwasher',
	'Online Captcha Typist',
	'Pharmacist',
	'Doorman',
	'Tour Gide',
	'Crime Scene Cleaner',
	'Slaughterhouse Worker',
	'Stylist',
	'Real Estate Agent',
	'Rapper',
	'Flight Attendant',
	'Dog Walker',
	'Librarian',
	'Archaeologist',
	'Veterinarian',
	'Accountant',
	'Police Officer',
	'Politician',
	'Lawyer',
	'Screenwriter',
	'Virtual Reality Developer',
	'Life Coach',
	'Bartender',
	'Doctor of Philosophy in Social Justice',
	'Ornithologist',
	'Waiter/Waitress',
	'Crowdfunding Organizer',
	'Privacy Specialist',
	'Drug Dealer',
	'Priest',
	'Nun',
	'Marijuana Farmer',
	'Cartoon creator',
	'Olympic Ice Skater'
]

export const normalJobs = [
	'General of the Army',
	'Social Worker',
	'Massage Therapist',
	'Firefighter',
	'Dentist',
	'Hairdresser',
	'Bodyguard',
	'Sexologist',
	'Cook',
	'UX Designer',
	'Plumber',
	'Meth Cooker',
	'Hacker'
]

export const goodJobs = [
	'Surgeon',
	'Biologist',
	'Psychiatrist',
	'Electrician',
	'Software Developer',
	'Nurse',
	'School Teacher',
	'Fitness Trainer',
	'Mechanic',
	'Doctor',
	'Drone Pilot',
	'Food Engineer',
	'Architect',
	'Robotics Engineer',
	'Custom Implant Organ Designer',
	'Geologist',
	'Botanist',
	'Chemist',
	'Physician',
	'Miner',
	'Microbiologist',
	'Meteorologist',
	'Farmer',
	'Midwife',
]

export const jobs = [...badJobs, ...normalJobs, ...goodJobs];

export const jobMasteryLevels = ['little experience or just bad', 'good', 'best'];