export const badPersonalityTraits = [
	'boring',
	'anger issues',
	'lazy',
	'satanist',
	'jehovah witness',
	'always telling spoilers',
	'communist',
	'curse a lot',
	'passive-aggressive',
	'abusive in relationships',
	'was in a prison for a murder',
	'can\'t accept that he/she was wrong',
	'radical feminist',
	'acts like Sheldon Cooper',
	'very naive',
	'likes to tell racist jokes',
	'has a lot of secrets',
	'drug addict',
	'alcoholic',
	'hates children',
	'drag queen',
]